### ISSUE TITLE
Trivial for tracking ERC20 Tokens

### ISSUE THREAD

**Issue by Wonderbeest** [shillhouse/rocketfuel#1]
**Trivial ** 

**Trivial is an ERC20 token catalog, that has profiles for 500+ tokens on Ethereum**

**https://trivial.co** 

**Tracker 

**Gives news and updates about tokens, some onchain metrics (DAUs, Holders), allows you to follow a selection to personalize feed**

**Comment by shillhouse** [comment]
Sorry for the long wait, adding it now!
